### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Jordantan1999** [jisong316/durg-recommendation#2]
I have a few question for the project

1. Is this collaborative filtering or content-based filtering? 
2. Why does it need machine learning

**Comment by jisong316** [comment]
1. Non of them as my codes doesn't include the recommender system part.
2. Most of my codes are natural language processing if you look at them closely. The point is to draw an insight using natural language processing and topic modeling which are machine learning algorithms. The actual dataset is very big, and you can't read them all manually, that's why people use machine learning to process those kind of data, in my case here are CountVectorizer with bigram for processing the language data and LDA model for topic modeling.

Sorry for the late response, but this repo is not monitored/updated regularly as I'm working in a different industry right now.
